import { db } from "./db";
import { safeStations, educationalResources } from "@shared/schema";

export async function seedDatabase() {
  const existingStations = await db.select().from(safeStations);
  if (existingStations.length > 0) return;

  console.log("Seeding database...");

  await db.insert(safeStations).values([
    { name: "Hospital Josina Machel", address: "Rua Major Kanhangulo, Ingombota, Luanda", phone: "222337244", province: "Luanda", municipality: "Ingombota", latitude: -8.8147, longitude: 13.2302, type: "hospital", isVerified: true },
    { name: "Hospital Militar Principal", address: "Av. Deolinda Rodrigues, Luanda", phone: "222321000", province: "Luanda", municipality: "Maianga", latitude: -8.8300, longitude: 13.2250, type: "hospital", isVerified: true },
    { name: "Hospital Pediátrico David Bernardino", address: "Rua Amilcar Cabral, Luanda", phone: "222330462", province: "Luanda", municipality: "Maianga", latitude: -8.8350, longitude: 13.2340, type: "hospital", isVerified: true },
    { name: "Maternidade Lucrécia Paím", address: "Luanda Centro", phone: "222339595", province: "Luanda", municipality: "Ingombota", latitude: -8.8180, longitude: 13.2350, type: "hospital", isVerified: true },
    { name: "Hospital Américo Boavida", address: "Luanda", phone: "222391411", province: "Luanda", municipality: "Samba", latitude: -8.8400, longitude: 13.2500, type: "hospital", isVerified: true },
    { name: "Esquadra da Polícia - Maianga", address: "Bairro Maianga, Luanda", phone: "113", province: "Luanda", municipality: "Maianga", latitude: -8.8380, longitude: 13.2350, type: "police", isVerified: true },
    { name: "SIC - Serviço de Investigação Criminal", address: "Rua Direita de Luanda", phone: "113", province: "Luanda", municipality: "Ingombota", latitude: -8.8100, longitude: 13.2350, type: "police", isVerified: true },
    { name: "Comando Provincial da Polícia - Luanda", address: "Luanda Centro", phone: "113", province: "Luanda", municipality: "Ingombota", latitude: -8.8150, longitude: 13.2300, type: "police", isVerified: true },
    { name: "Rede Mulher Angola", address: "Luanda Centro", phone: "222390988", province: "Luanda", municipality: "Maianga", latitude: -8.8200, longitude: 13.2400, type: "ngo", isVerified: true },
    { name: "INAC - Instituto Nacional da Criança", address: "Luanda", phone: "145", province: "Luanda", municipality: "Maianga", latitude: -8.8250, longitude: 13.2380, type: "ngo", isVerified: true },
    { name: "MINFAMU - Ministério da Família", address: "Luanda", phone: "222393100", province: "Luanda", municipality: "Ingombota", latitude: -8.8160, longitude: 13.2320, type: "ngo", isVerified: true },
    { name: "Associação Mãos Livres", address: "Luanda", phone: "923456789", province: "Luanda", municipality: "Viana", latitude: -8.8900, longitude: 13.3700, type: "ngo", isVerified: true },
    { name: "Centro de Acolhimento Maianga", address: "Bairro Maianga, Luanda", phone: "222321456", province: "Luanda", municipality: "Maianga", latitude: -8.8383, longitude: 13.2344, type: "shelter", isVerified: true },
    { name: "Centro de Aconselhamento - Viana", address: "Viana, Luanda", phone: "222640100", province: "Luanda", municipality: "Viana", latitude: -8.8950, longitude: 13.3750, type: "shelter", isVerified: true },
    { name: "Hospital Provincial do Huambo", address: "Cidade do Huambo", phone: "241221100", province: "Huambo", municipality: "Huambo", latitude: -12.7761, longitude: 15.7392, type: "hospital", isVerified: true },
    { name: "Hospital Central de Benguela", address: "Cidade de Benguela", phone: "272222100", province: "Benguela", municipality: "Benguela", latitude: -12.5763, longitude: 13.4055, type: "hospital", isVerified: true },
    { name: "Hospital Provincial de Cabinda", address: "Cidade de Cabinda", phone: "231221100", province: "Cabinda", municipality: "Cabinda", latitude: -5.5577, longitude: 12.1959, type: "hospital", isVerified: true },
    { name: "Esquadra da Polícia - Benguela", address: "Benguela Centro", phone: "113", province: "Benguela", municipality: "Benguela", latitude: -12.5780, longitude: 13.4070, type: "police", isVerified: true },
    { name: "Esquadra da Polícia - Huambo", address: "Huambo Centro", phone: "113", province: "Huambo", municipality: "Huambo", latitude: -12.7770, longitude: 15.7400, type: "police", isVerified: true },
  ]);

  await db.insert(educationalResources).values([
    { title: "O que é violência de género?", content: "A violência de género inclui qualquer acto de violência que resulte, ou possa resultar, em dano físico, sexual, psicológico ou económico para a mulher ou menina, incluindo ameaças, coerção ou privação da liberdade. Inclui:\n\n- Violência física: agressões, empurrões, queimaduras\n- Violência psicológica: humilhações, ameaças, controlo excessivo\n- Violência sexual: qualquer acto sexual forçado\n- Violência económica: controlo de dinheiro, impedir de trabalhar\n- Violência patrimonial: destruição de bens pessoais", category: "conhecimento", icon: "information-circle", orderIndex: 1 },
    { title: "Reconheça os sinais de alerta", content: "Sinais de que você ou alguém pode estar em situação de violência:\n\n- O parceiro controla onde vai, com quem fala ou o que veste\n- Isolamento da família e amigos\n- Ciúmes excessivos e possessividade\n- Gritos, insultos e humilhações frequentes\n- Destruição de objectos pessoais\n- Ameaças de violência contra si ou contra os filhos\n- Pressão ou forçar relações sexuais\n- Controlo do dinheiro e das finanças\n- Verificação constante do telemóvel\n\nSe reconhece 3 ou mais destes sinais, procure ajuda.", category: "prevencao", icon: "alert-circle", orderIndex: 2 },
    { title: "Violência contra menores", content: "Crianças e adolescentes merecem protecção especial:\n\n- Todo o abuso sexual contra menores é crime em Angola\n- A denúncia é obrigatória para quem tiver conhecimento\n- O INAC (145) recebe denúncias de violência contra menores\n- Sinais em crianças: medo excessivo de adultos, mudança repentina de comportamento, lesões inexplicáveis, isolamento\n- Casamento infantil é ilegal em Angola\n\nDireitos da criança pela Lei de Protecção da Criança de Angola:\n- Direito à integridade física e psicológica\n- Direito à protecção contra exploração\n- Direito a ser ouvida", category: "menores", icon: "people", orderIndex: 3 },
    { title: "Os seus direitos legais", content: "Em Angola, a violência doméstica é crime (Lei 25/11):\n\n- Tem direito a apresentar queixa na polícia (113)\n- Pode solicitar medida de protecção ao tribunal\n- Os agressores podem ser presos e julgados\n- Tem direito a assistência médica gratuita\n- Os seus filhos são protegidos pela lei\n\nLeis importantes:\n- Lei Contra a Violência Doméstica (25/11)\n- Código Penal Angolano\n- Lei de Protecção da Criança\n- Lei de Proteção de Dados Pessoais\n\nNenhuma tradição ou costume justifica a violência.", category: "direitos", icon: "shield-checkmark", orderIndex: 4 },
    { title: "Plano de segurança pessoal", content: "Se está em situação de perigo, prepare um plano:\n\n1. Memorize os números de emergência: Polícia (113), Bombeiros (190), Criança (145), Mulher (180)\n2. Tenha sempre documentos importantes prontos (BI, certidões)\n3. Guarde dinheiro de emergência num local seguro\n4. Identifique vizinhos ou locais seguros para fugir\n5. Combine um código secreto com alguém de confiança\n6. Configure este app no disfarce de calculadora\n7. Mantenha o telemóvel sempre carregado\n8. Saiba onde ficam os postos seguros mais próximos\n9. Se possível, guarde roupa e itens essenciais num saco pronto\n10. Confie no seu instinto - se sente perigo, procure ajuda", category: "seguranca", icon: "lock-closed", orderIndex: 5 },
    { title: "Onde procurar ajuda em Angola", content: "Recursos disponíveis:\n\nLinhas de emergência:\n- Polícia Nacional: 113\n- Bombeiros: 190\n- Linha da Criança (INAC): 145\n- Linha da Mulher: 180\n\nOrganizações:\n- Rede Mulher Angola: apoio jurídico e psicológico\n- MINFAMU: Ministério da Família, apoio institucional\n- Associação Mãos Livres: apoio a vítimas\n- INAC: protecção de crianças\n\nHospitais com atendimento especializado:\n- Hospital Josina Machel (Luanda)\n- Maternidade Lucrécia Paím (Luanda)\n\nUse este app para encontrar o posto seguro mais próximo.", category: "ajuda", icon: "heart", orderIndex: 6 },
    { title: "Como apoiar uma vítima", content: "Se conhece alguém em situação de violência:\n\n- Ouça sem julgar - não pergunte 'porque não saiu?'\n- Acredite na pessoa - falsas denúncias são raras\n- Não force decisões - respeite o tempo da vítima\n- Ofereça ajuda prática (abrigo, transporte, comida)\n- Partilhe informações sobre recursos disponíveis\n- Mantenha confidencialidade absoluta\n- Não confronte o agressor directamente\n- Ajude a criar um plano de segurança\n- Esteja disponível sem pressionar\n\nA sua presença e apoio podem salvar uma vida.", category: "apoio", icon: "hand-left", orderIndex: 7 },
    { title: "Violência digital e tecnológica", content: "Formas de violência online:\n\n- Monitorização do telemóvel sem consentimento\n- Partilha de fotos íntimas sem autorização\n- Cyberstalking e perseguição online\n- Controlo de redes sociais\n- Ameaças por mensagens\n\nComo se proteger:\n- Use senhas fortes e diferentes para cada conta\n- Active a verificação em 2 passos\n- Não partilhe localização em tempo real\n- Use este app com disfarce para proteger a sua privacidade\n- Denuncie assédio online à polícia\n- A partilha não consentida de imagens íntimas é crime", category: "digital", icon: "phone-portrait", orderIndex: 8 },
  ]);

  console.log("Database seeded successfully");
}
